import { useState, useEffect } from "react";
import { Slider } from "@/components/ui/slider";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button";
import { Calculator, Download, TrendingUp, Users, DollarSign, MousePointer, Target, Sparkles } from "lucide-react";

const audiences = [
  { value: "ecommerce", label: "E-commerce Buyers", ctr: 2.8, cpc: 1.2, conv: 3.5 },
  { value: "b2b", label: "B2B Decision Makers", ctr: 1.9, cpc: 4.5, conv: 2.1 },
  { value: "saas", label: "SaaS Users", ctr: 2.4, cpc: 3.2, conv: 2.8 },
  { value: "local", label: "Local Services", ctr: 3.2, cpc: 0.9, conv: 4.2 },
  { value: "luxury", label: "Luxury Consumers", ctr: 1.5, cpc: 5.8, conv: 1.8 },
];

export function ImpactSimulator() {
  const [budget, setBudget] = useState([5000]);
  const [audience, setAudience] = useState("ecommerce");
  const [isSimulating, setIsSimulating] = useState(false);
  const [showResults, setShowResults] = useState(false);
  const [animatedValues, setAnimatedValues] = useState({
    impressions: 0,
    clicks: 0,
    ctr: 0,
    cpc: 0,
    conversions: 0,
    revenue: 0,
    roas: 0
  });

  const selectedAudience = audiences.find(a => a.value === audience)!;
  
  const calculateResults = () => {
    const clicks = Math.round(budget[0] / selectedAudience.cpc);
    const impressions = Math.round(clicks / (selectedAudience.ctr / 100));
    const conversions = Math.round(clicks * (selectedAudience.conv / 100));
    const avgOrderValue = audience === "luxury" ? 450 : audience === "b2b" ? 2500 : 85;
    const revenue = conversions * avgOrderValue;
    const roas = revenue / budget[0];

    return {
      impressions,
      clicks,
      ctr: selectedAudience.ctr,
      cpc: selectedAudience.cpc,
      conversions,
      revenue,
      roas
    };
  };

  const runSimulation = () => {
    setIsSimulating(true);
    setShowResults(false);
    
    const finalResults = calculateResults();
    
    // Animate values counting up
    let progress = 0;
    const interval = setInterval(() => {
      progress += 0.05;
      if (progress >= 1) {
        progress = 1;
        clearInterval(interval);
        setIsSimulating(false);
        setShowResults(true);
      }
      
      setAnimatedValues({
        impressions: Math.round(finalResults.impressions * progress),
        clicks: Math.round(finalResults.clicks * progress),
        ctr: Number((finalResults.ctr * progress).toFixed(1)),
        cpc: Number((finalResults.cpc * progress).toFixed(2)),
        conversions: Math.round(finalResults.conversions * progress),
        revenue: Math.round(finalResults.revenue * progress),
        roas: Number((finalResults.roas * progress).toFixed(1))
      });
    }, 50);
  };

  const downloadReport = () => {
    const report = `
HireMediaMind - Ad Impact Simulation Report
============================================

Budget: $${budget[0].toLocaleString()}
Target Audience: ${selectedAudience.label}

Projected Results:
- Impressions: ${animatedValues.impressions.toLocaleString()}
- Clicks: ${animatedValues.clicks.toLocaleString()}
- CTR: ${animatedValues.ctr}%
- CPC: $${animatedValues.cpc}
- Conversions: ${animatedValues.conversions}
- Projected Revenue: $${animatedValues.revenue.toLocaleString()}
- ROAS: ${animatedValues.roas}x

Generated by HireMediaMind AI
https://www.hiremediamind.com
    `;
    
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'ad-impact-simulation.txt';
    a.click();
  };

  return (
    <section className="section-padding relative overflow-hidden bg-muted/30">
      {/* Background Effects */}
      <div className="absolute inset-0 aurora-bg opacity-30" />
      <div className="absolute inset-0 grid-pattern opacity-10" />
      
      <div className="relative mx-auto max-w-7xl px-4">
        {/* Section Header */}
        <div className="mb-16 text-center">
          <span className="section-badge mb-4 inline-flex items-center gap-2">
            <Calculator className="h-4 w-4" />
            Impact Simulator
          </span>
          <h2 className="font-display text-3xl font-bold text-foreground md:text-4xl lg:text-5xl mb-4">
            Simulate Your Ad Impact
          </h2>
          <p className="max-w-2xl mx-auto text-muted-foreground text-lg">
            See projected results before you spend. Adjust budget and audience to preview your potential ROI.
          </p>
        </div>

        <div className="grid gap-8 lg:grid-cols-2">
          {/* Controls Panel */}
          <div className="glass-card-premium rounded-3xl p-8 space-y-8">
            <div className="flex items-center gap-3 mb-6">
              <div className="h-12 w-12 rounded-2xl bg-primary/10 flex items-center justify-center">
                <Target className="h-6 w-6 text-primary" />
              </div>
              <div>
                <h3 className="font-semibold text-foreground">Campaign Settings</h3>
                <p className="text-sm text-muted-foreground">Configure your simulation parameters</p>
              </div>
            </div>

            {/* Budget Slider */}
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <label className="text-sm font-medium text-foreground">Monthly Ad Budget</label>
                <span className="text-2xl font-bold gradient-text">${budget[0].toLocaleString()}</span>
              </div>
              <Slider
                value={budget}
                onValueChange={setBudget}
                min={1000}
                max={50000}
                step={500}
                className="w-full"
              />
              <div className="flex justify-between text-xs text-muted-foreground">
                <span>$1,000</span>
                <span>$50,000</span>
              </div>
            </div>

            {/* Audience Select */}
            <div className="space-y-3">
              <label className="text-sm font-medium text-foreground">Target Audience</label>
              <Select value={audience} onValueChange={setAudience}>
                <SelectTrigger className="w-full h-12 rounded-xl bg-background/50">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {audiences.map((aud) => (
                    <SelectItem key={aud.value} value={aud.value}>
                      <div className="flex items-center gap-2">
                        <Users className="h-4 w-4 text-muted-foreground" />
                        {aud.label}
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            {/* Audience Stats Preview */}
            <div className="grid grid-cols-3 gap-3 p-4 rounded-xl bg-muted/50">
              <div className="text-center">
                <p className="text-xs text-muted-foreground mb-1">Avg CTR</p>
                <p className="font-semibold text-primary">{selectedAudience.ctr}%</p>
              </div>
              <div className="text-center border-x border-border">
                <p className="text-xs text-muted-foreground mb-1">Avg CPC</p>
                <p className="font-semibold text-secondary">${selectedAudience.cpc}</p>
              </div>
              <div className="text-center">
                <p className="text-xs text-muted-foreground mb-1">Conv Rate</p>
                <p className="font-semibold text-emerald">{selectedAudience.conv}%</p>
              </div>
            </div>

            {/* Simulate Button */}
            <Button 
              onClick={runSimulation} 
              disabled={isSimulating}
              className="w-full h-14 btn-primary text-base"
            >
              {isSimulating ? (
                <>
                  <div className="h-5 w-5 animate-spin rounded-full border-2 border-current border-t-transparent mr-2" />
                  Calculating Results...
                </>
              ) : (
                <>
                  <Sparkles className="h-5 w-5 mr-2" />
                  Simulate Campaign Impact
                </>
              )}
            </Button>
          </div>

          {/* Results Panel */}
          <div className="glass-card-premium rounded-3xl p-8">
            <div className="flex items-center justify-between mb-6">
              <div className="flex items-center gap-3">
                <div className="h-12 w-12 rounded-2xl bg-emerald/10 flex items-center justify-center">
                  <TrendingUp className="h-6 w-6 text-emerald" />
                </div>
                <div>
                  <h3 className="font-semibold text-foreground">Projected Results</h3>
                  <p className="text-sm text-muted-foreground">Based on industry benchmarks</p>
                </div>
              </div>
              {showResults && (
                <Button variant="outline" size="sm" onClick={downloadReport} className="gap-2">
                  <Download className="h-4 w-4" />
                  Download
                </Button>
              )}
            </div>

            {/* Results Grid */}
            <div className="grid grid-cols-2 gap-4 mb-6">
              <div className="p-4 rounded-xl bg-gradient-to-br from-primary/5 to-primary/10 border border-primary/10 result-card">
                <div className="flex items-center gap-2 mb-2">
                  <Users className="h-4 w-4 text-primary" />
                  <span className="text-xs text-muted-foreground">Impressions</span>
                </div>
                <p className="text-2xl font-bold text-foreground">{animatedValues.impressions.toLocaleString()}</p>
              </div>
              
              <div className="p-4 rounded-xl bg-gradient-to-br from-secondary/5 to-secondary/10 border border-secondary/10 result-card">
                <div className="flex items-center gap-2 mb-2">
                  <MousePointer className="h-4 w-4 text-secondary" />
                  <span className="text-xs text-muted-foreground">Clicks</span>
                </div>
                <p className="text-2xl font-bold text-foreground">{animatedValues.clicks.toLocaleString()}</p>
              </div>
              
              <div className="p-4 rounded-xl bg-gradient-to-br from-accent/5 to-accent/10 border border-accent/10 result-card">
                <div className="flex items-center gap-2 mb-2">
                  <Target className="h-4 w-4 text-accent" />
                  <span className="text-xs text-muted-foreground">Conversions</span>
                </div>
                <p className="text-2xl font-bold text-foreground">{animatedValues.conversions}</p>
              </div>
              
              <div className="p-4 rounded-xl bg-gradient-to-br from-emerald/5 to-emerald/10 border border-emerald/10 result-card">
                <div className="flex items-center gap-2 mb-2">
                  <DollarSign className="h-4 w-4 text-emerald" />
                  <span className="text-xs text-muted-foreground">Revenue</span>
                </div>
                <p className="text-2xl font-bold text-foreground">${animatedValues.revenue.toLocaleString()}</p>
              </div>
            </div>

            {/* ROAS Highlight */}
            <div className="p-6 rounded-2xl bg-gradient-to-r from-primary/10 via-secondary/10 to-emerald/10 border border-primary/20 text-center">
              <p className="text-sm text-muted-foreground mb-2">Projected Return on Ad Spend</p>
              <p className="text-5xl font-bold gradient-text mb-2">{animatedValues.roas}x</p>
              <p className="text-xs text-muted-foreground">
                For every $1 spent, you could earn ${animatedValues.roas.toFixed(2)}
              </p>
            </div>

            {/* Disclaimer */}
            {showResults && (
              <p className="mt-4 text-xs text-muted-foreground text-center animate-fade-in">
                * Projections based on industry averages. Actual results may vary.
              </p>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
