import jsPDF from 'jspdf';
import logo from '@/assets/logo.png'; // Make sure this path is valid, or use a base64 string if needed for PDF

interface PartnerData {
    name: string;
    role: string;
    joining_date: string;
    scope_of_work: string;
    revenue_model: string;
    document_id: string;
    date: string;
}

interface EmployeeData {
    name: string;
    designation: string;
    salary: string;
    joining_date: string;
    type: string;
    document_id: string;
    date: string;
}

export const generatePartnerPDF = (data: PartnerData) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(25, 25, 35);
    doc.text('HireMediaMind Automation LLP', 20, 20);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('New Delhi, India | www.hiremediamind.com', 20, 26);

    doc.setDrawColor(200, 200, 200);
    doc.line(20, 30, 190, 30);

    // Title
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('PARTNERSHIP APPOINTMENT LETTER', 105, 50, { align: 'center' });

    // Body
    doc.setFontSize(11);
    doc.text(`This Partnership Appointment Letter is made on ${data.date}`, 20, 70);
    doc.text('BETWEEN', 105, 80, { align: 'center' });
    doc.text('HireMediaMind Automation LLP, hereinafter referred to as "Company",', 20, 90);
    doc.text('AND', 105, 100, { align: 'center' });
    doc.text(`${data.name}, hereinafter referred to as "Partner".`, 20, 110);

    // Sections
    let y = 130;

    doc.setFont("helvetica", "bold");
    doc.text('1. Appointment:', 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(`The Company appoints ${data.name} as ${data.role} effective from ${data.joining_date}.`, 20, y + 6);

    y += 20;
    doc.setFont("helvetica", "bold");
    doc.text('2. Scope of Work:', 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(doc.splitTextToSize(data.scope_of_work, 170), 20, y + 6);

    y += 20;
    doc.setFont("helvetica", "bold");
    doc.text('3. Revenue Sharing:', 20, y);
    doc.setFont("helvetica", "normal");
    doc.text(data.revenue_model, 20, y + 6);

    y += 20;
    doc.setFont("helvetica", "bold");
    doc.text('4. Nature of Relationship:', 20, y);
    doc.setFont("helvetica", "normal");
    doc.text('This is a partnership association and does not constitute an employer-employee relationship.', 20, y + 6);

    // Footer / Signatures
    y += 50;
    doc.text('__________________________', 20, y);
    doc.text('Authorized Signatory', 20, y + 6);
    doc.text('HireMediaMind Automation LLP', 20, y + 12);

    doc.text('__________________________', 140, y);
    doc.text('Partner Signature', 140, y + 6);

    // Watermark if revoked
    // (Logic can be added here if we pass status)

    // Document ID Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Document ID: ${data.document_id} | Generated by System`, 105, 290, { align: 'center' });

    doc.save(`${data.document_id}_${data.name}_Partnership.pdf`);
};

export const generateEmployeePDF = (data: EmployeeData) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(25, 25, 35);
    doc.text('HireMediaMind Automation LLP', 20, 20);

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('New Delhi, India | www.hiremediamind.com', 20, 26);

    doc.line(20, 30, 190, 30);

    // Title
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text('EMPLOYMENT OFFER LETTER', 105, 50, { align: 'center' });

    // Body
    doc.setFontSize(11);
    doc.text(`Date: ${data.date}`, 160, 60);

    doc.text(`Dear ${data.name},`, 20, 70);
    doc.text(`We are pleased to offer you the position of ${data.designation} at HireMediaMind Automation LLP.`, 20, 80);

    // Details
    let y = 100;

    const details = [
        { label: 'Joining Date:', value: data.joining_date },
        { label: 'Employment Type:', value: data.type },
        { label: 'Compensation:', value: data.salary },
        { label: 'Probation Period:', value: '3 Months' },
        { label: 'Location:', value: 'Remote / New Delhi' },
    ];

    details.forEach(item => {
        doc.setFont("helvetica", "bold");
        doc.text(item.label, 20, y);
        doc.setFont("helvetica", "normal");
        doc.text(item.value, 70, y);
        y += 10;
    });

    y += 10;
    doc.text('We look forward to having you on our team. Please sign and return a copy of this letter.', 20, y);

    // Signatures
    y += 40;
    doc.text('__________________________', 20, y);
    doc.text('Authorized Signatory', 20, y + 6);
    doc.text('HireMediaMind Automation LLP', 20, y + 12);

    doc.text('__________________________', 140, y);
    doc.text('Employee Signature', 140, y + 6);

    // Document ID Footer
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Document ID: ${data.document_id} | Generated by System`, 105, 290, { align: 'center' });

    doc.save(`${data.document_id}_${data.name}_OfferLetter.pdf`);
};
