import { useState, useEffect } from "react";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useToast } from "@/components/ui/use-toast";
import { FileText, Download, Filter } from "lucide-react";
import { Button } from "@/components/ui/button";

interface Document {
    id: number;
    doc_id: string;
    entity_type: string;
    entity_name: string;
    generated_date: string;
    status: string;
}

export default function Documents() {
    const [documents, setDocuments] = useState<Document[]>([]);
    const [isLoading, setIsLoading] = useState(true);
    const { toast } = useToast();

    useEffect(() => {
        fetchDocuments();
    }, []);

    const fetchDocuments = async () => {
        try {
            const response = await fetch('/api/admin/hr/documents.php', {
                headers: { 'Authorization': `Bearer ${localStorage.getItem('admin_token')}` }
            });
            const data = await response.json();
            if (Array.isArray(data)) setDocuments(data);
        } catch (error) {
            toast({ title: "Error", description: "Failed to load documents", variant: "destructive" });
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="p-8 space-y-8">
            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-3xl font-bold tracking-tight">Document Registry</h1>
                    <p className="text-muted-foreground">Central repository of all legal documents generated by the system.</p>
                </div>
                <Button variant="outline"><Filter className="mr-2 h-4 w-4" /> Filter</Button>
            </div>

            <div className="rounded-md border">
                <Table>
                    <TableHeader>
                        <TableRow>
                            <TableHead>Document ID</TableHead>
                            <TableHead>Entity Name</TableHead>
                            <TableHead>Type</TableHead>
                            <TableHead>Date Generated</TableHead>
                            <TableHead>Status</TableHead>
                            <TableHead className="text-right">Actions</TableHead>
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {documents.map((doc) => (
                            <TableRow key={doc.id}>
                                <TableCell className="font-mono text-xs">{doc.doc_id}</TableCell>
                                <TableCell className="font-medium">{doc.entity_name}</TableCell>
                                <TableCell>
                                    <span className={`px-2 py-1 rounded-full text-xs border ${doc.entity_type === 'Partner' ? 'bg-blue-50 border-blue-200 text-blue-700' : 'bg-purple-50 border-purple-200 text-purple-700'
                                        }`}>
                                        {doc.entity_type}
                                    </span>
                                </TableCell>
                                <TableCell>{new Date(doc.generated_date).toLocaleDateString()}</TableCell>
                                <TableCell>
                                    <span className={`px-2 py-1 rounded-full text-xs ${doc.status === 'Active' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
                                        }`}>
                                        {doc.status}
                                    </span>
                                </TableCell>
                                <TableCell className="text-right">
                                    <Button variant="ghost" size="sm">
                                        <Download className="h-4 w-4" />
                                    </Button>
                                </TableCell>
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </div>
        </div>
    );
}
